apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod overlay — bumps replicas + resource limits for live traffic.
namespace: chef-v-game
resources:
  - ../../base
images:
  - name: ghcr.io/seekn/chef-v-game-frontend
    newName: ghcr.io/joseph118789-max/chef-v-game-frontend
    newTag: dev
patches:
  - target:
      kind: Deployment
      name: chef-v-game
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
