apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod overlay — bumps replicas + resource limits for live traffic.
namespace: chef-v-game
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: chef-v-game
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi